ip = input('Digite um endereco IP: ')
print('O endereco ip: %s e valido' % ip)
print('O endereco ip: %s tem o tamanho de %d caracteres' %(ip,len(ip)))
print('O endereco ip: %s tem o tamanho de %s caracteres' %(ip,str(len(ip))))
print('Numero quebrado %.2f' % 1.24567)